version: '3'

services:
  keycloak:
    container_name: KeycloakTest
    ports:
      - 8080:8080
    image: quay.io/keycloak/keycloak:17.0.1
    volumes:
      - /keycloak:/usr/keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_USER=user
      - KEYCLOAK_PASSWORD=user
    command: start-dev

  frontend:
    container_name: FrontEnd
    ports:
      - 3000:3000
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/frontend
    restart: on-failure