version: '3'

services:
  keycloak:
    container_name: KeycloakTest
    ports:
      - 8080:8080
    image: quay.io/keycloak/keycloak:17.0.1
    volumes:
      - /keycloak:/usr/keycloak
    env_file:
      - ./keycloak/.env
    command: start-dev

  frontend:
    container_name: FrontEnd
    ports:
      - 3000:3000
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/frontend
    restart: on-failure