version: '3'

services:
  keycloak:
    container_name: KeycloakTest
    ports:
      - 8080:8080
    image: quay.io/keycloak/keycloak:17.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev